version: '3'

services:
  reviews:
    build: reviewsAPI/
    depends_on:
      - 'db'
    ports:
      - '4000:4000'

  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: retaildb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./reviewsAPI/dbsql/dataClean:/tmp


